### PR TITLE
Get the usb device's name

### PR DESCRIPTION
**Pull request by asmasma21**

### CODE REVIEW

**Comment by rednaks** [comment]
Note that not all Linux distribution are mounting usb devices on /media/ some are mounting on /mnt/ and I think that using /dev/disk/by-id/usb\* is better !

**Comment by asmasma21** [comment]
i can't find a solution in which i can use /dev/disk/by-id/usb\* :s

**Comment by rednaks** [comment]
well you can use that id found with the udisks command,  
udisks --show-info /dev/disk/usb\*  ...

**Comment by spaceinvadertn** [comment]
simple tu  parcours le /dev/disk/ est tu récupére tout ce qui ce trouve
dedans dans une liste   la tu aura un tableau dans lequel il contient tt
les id :)

2013/3/5 Alexandre BM notifications@github.com

> well you can that id found with the udisks command,
> 
> udisks --show-info /dev/disk/usb\* ...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ClubEspritLibre/the-Gnu-Distro/pull/4#issuecomment-14466629
> .

## 

Cdt,
Omar Ferchichi

**Comment by rednaks** [comment]
Je tiens à rappeler que le but est de trouver le point de montage de la clé usb !

**Comment by rednaks** [comment]
@asmasma21  I'll make a little tutorial about disks later before we start !

**Comment by asmasma21** [comment]
cc @rednaks can you please close the pull request ? :)

**Comment by rednaks** [comment]
It's not necessary to close the PR, when you pushed the changes it updates the PR ;) thankd !

**Comment by asmasma21** [comment]
Okk .. I thought that i have to send a pull request for every commit :D .. Thnx

**Pull request merged**
